name: Lint GitHub Actions Workflows
on:
  push:
    paths:
      - '.github/workflows/**.yml'

jobs:
  actionlint:
    name: Lint GitHub Actions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Lint workflow files
        uses: docker://rhysd/actionlint:1.6.22
        with:
          args: -color

  checkVersions:
    name: Check for pinned verions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Ensure SHA pinned actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@af2eb3226618e2494e3d9084f515ad6dcf16e229
        with:
          allowlist: |
            actions/
